name: Publish to GitHub pages
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Build
        run: npm ci --omit=dev
      - name: Delete .gitignore
        run: rm .gitignore
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .
